export const DataSakit = [
  {
    pasienId: 11,
    jenispenyakit: "Flu",
    kesadaran: "Baik",
    suhu: 38,
    tanggal: "2014-01-01",
  },
  {
    pasienId: 12,
    jenispenyakit: "Demam",
    kesadaran: "Sedang",
    suhu: 39,
    tanggal: "2014-02-01",
  },
  {
    pasienId: 13,
    jenispenyakit: "Batuk",
    kesadaran: "Baik",
    suhu: 37,
    tanggal: "2023-03-01",
  },
  {
    pasienId: 14,
    jenispenyakit: "Pusing",
    kesadaran: "Sedang",
    suhu: 36,
    tanggal: "2013-04-01",
  },
  {
    pasienId: 15,
    jenispenyakit: "Sakit Tenggorokan",
    kesadaran: "Baik",
    suhu: 37,
    tanggal: "2023-05-01",
  },
  {
    pasienId: 16,
    jenispenyakit: "Diare",
    kesadaran: "Sedang",
    suhu: 38,
    tanggal: "2020-06-01",
  },
  {
    pasienId: 17,
    jenispenyakit: "Mual",
    kesadaran: "Baik",
    suhu: 36,
    tanggal: "2021-07-01",
  },
  {
    pasienId: 18,
    jenispenyakit: "Sakit Kepala",
    kesadaran: "Sedang",
    suhu: 37,
    tanggal: "2023-08-01",
  },
  {
    pasienId: 19,
    jenispenyakit: "Asma",
    kesadaran: "Baik",
    suhu: 35,
    tanggal: "2024-09-01",
  },
  {
    pasienId: 20,
    jenispenyakit: "Hipertensi",
    kesadaran: "Sedang",
    suhu: 36,
    tanggal: "2021-10-01",
  },
  {
    pasienId: 21,
    jenispenyakit: "Flu",
    kesadaran: "Baik",
    suhu: 38,
    tanggal: "2021-11-01",
  },
  {
    pasienId: 22,
    jenispenyakit: "Demam",
    kesadaran: "Sedang",
    suhu: 39,
    tanggal: "2021-12-01",
  },
  {
    pasienId: 23,
    jenispenyakit: "Batuk",
    kesadaran: "Baik",
    suhu: 37,
    tanggal: "2024-01-01",
  },
  {
    pasienId: 24,
    jenispenyakit: "Pusing",
    kesadaran: "Sedang",
    suhu: 36,
    tanggal: "2024-02-01",
  },
  {
    pasienId: 25,
    jenispenyakit: "Sakit Tenggorokan",
    kesadaran: "Baik",
    suhu: 37,
    tanggal: "2024-03-01",
  },
  {
    pasienId: 26,
    jenispenyakit: "Diare",
    kesadaran: "Sedang",
    suhu: 38,
    tanggal: "2024-04-01",
  },
  {
    pasienId: 27,
    jenispenyakit: "Mual",
    kesadaran: "Baik",
    suhu: 36,
    tanggal: "2024-05-01",
  },
  {
    pasienId: 28,
    jenispenyakit: "Sakit Kepala",
    kesadaran: "Sedang",
    suhu: 37,
    tanggal: "2024-06-01",
  },
  {
    pasienId: 29,
    jenispenyakit: "Asma",
    kesadaran: "Baik",
    suhu: 35,
    tanggal: "2024-07-01",
  },
  {
    pasienId: 30,
    jenispenyakit: "Hipertensi",
    kesadaran: "Sedang",
    suhu: 36,
    tanggal: "2014-08-01",
  },
  {
    pasienId: 31,
    jenispenyakit: "Flu",
    kesadaran: "Baik",
    suhu: 38,
    tanggal: "2023-09-01",
  },
  {
    pasienId: 32,
    jenispenyakit: "Demam",
    kesadaran: "Sedang",
    suhu: 39,
    tanggal: "2019-10-01",
  },
  {
    pasienId: 33,
    jenispenyakit: "Batuk",
    kesadaran: "Baik",
    suhu: 37,
    tanggal: "2019-11-01",
  },
  {
    pasienId: 34,
    jenispenyakit: "Pusing",
    kesadaran: "Sedang",
    suhu: 36,
    tanggal: "2018-12-01",
  },
  {
    pasienId: 35,
    jenispenyakit: "Sakit Tenggorokan",
    kesadaran: "Baik",
    suhu: 37,
    tanggal: "2015-01-01",
  },
];
